---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: "Esta tarea limpia un workspace eliminando todos los archivos."
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/bin/sh
        set -eu
        echo "Eliminando todos los archivos de ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Eliminar archivos y directorios no ocultos
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Eliminar archivos y directorios ocultos (excepto ..)
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: "Argumentos para pasar a nosetests"
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        # Crear entorno virtual para aislar dependencias
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)